### ISSUE TITLE
Why do Airbnb’s coding standards recommend using named function expressions instead of function declarations?

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-urgent-action-pdfs#4]
https://github.com/airbnb/javascript#functions

**Comment by pauldwaite** [comment]
I’ve added an example file trying to demonstrate what they’re talking about:

https://github.com/wearethoughtfox/amnesty-urgent-action-pdfs/blob/master/example-function-naming.js

I’ve never actually had a problem caused by function name hoisting (i.e. being able to call a function before it’s defined) before, but maybe it’s an issue in larger codebases.

**Comment by robertocarroll** [comment]
Thanks for this explanation. I great way of showing it! 

How do you decide which approach to use?

**Comment by robertocarroll** [comment]
Thanks for adding this explanation. Very helpful.
